version: "3.7"

services:

  php:
    build:
      context: docker/
      dockerfile: phpextension
    restart: 'always'
    ports:
      - '80:80'
    volumes:
      - ./www:/var/www/html/
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redis:/data

  composer:
    image: composer:1.9
    command: ["composer", "install"]
    volumes:
      - ./www:/var/www/html/
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ANI7c2TuKclS5mu1298I
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
volumes:
  redis-data: